
INSERT INTO co.t_ingredients VALUES (1, 'cognac');
INSERT INTO co.t_ingredients VALUES (2, 'crème de cacao');
INSERT INTO co.t_ingredients VALUES (3, 'cream');
INSERT INTO co.t_ingredients VALUES (4, 'vermouth');
INSERT INTO co.t_ingredients VALUES (5, 'campari');
INSERT INTO co.t_ingredients VALUES (6, 'soda water');
INSERT INTO co.t_ingredients VALUES (7, 'gin');
INSERT INTO co.t_ingredients VALUES (8, 'calvados');
INSERT INTO co.t_ingredients VALUES (9, 'apricot brandy');
INSERT INTO co.t_ingredients VALUES (10, 'maraschino');
INSERT INTO co.t_ingredients VALUES (11, 'crème de violette');
INSERT INTO co.t_ingredients VALUES (12, 'rum');
INSERT INTO co.t_ingredients VALUES (13, 'triple sec');
INSERT INTO co.t_ingredients VALUES (14, 'white rum');
INSERT INTO co.t_ingredients VALUES (15, 'lemon juice');
INSERT INTO co.t_ingredients VALUES (16, 'bourbon whiskey');
INSERT INTO co.t_ingredients VALUES (17, 'bourbon');
INSERT INTO co.t_ingredients VALUES (18, 'orange bitters');
INSERT INTO co.t_ingredients VALUES (19, 'whiskey');
INSERT INTO co.t_ingredients VALUES (20, 'sugar syrup');
INSERT INTO co.t_ingredients VALUES (21, 'carbonated water');
INSERT INTO co.t_ingredients VALUES (22, 'green chartreuse');
INSERT INTO co.t_ingredients VALUES (23, 'lime');
INSERT INTO co.t_ingredients VALUES (24, 'chartreuse');
INSERT INTO co.t_ingredients VALUES (25, 'maraschino liqueur');
INSERT INTO co.t_ingredients VALUES (26, 'rye whiskey');
INSERT INTO co.t_ingredients VALUES (27, 'angostura bitters');
INSERT INTO co.t_ingredients VALUES (28, 'grenadine');
INSERT INTO co.t_ingredients VALUES (29, 'dashes');
INSERT INTO co.t_ingredients VALUES (30, 'sugar');
INSERT INTO co.t_ingredients VALUES (31, 'water');
INSERT INTO co.t_ingredients VALUES (32, 'brandy');
INSERT INTO co.t_ingredients VALUES (33, 'orange juice');
INSERT INTO co.t_ingredients VALUES (34, 'scotch whisky');
INSERT INTO co.t_ingredients VALUES (35, 'drambuie');
INSERT INTO co.t_ingredients VALUES (36, 'crème de menthe');
INSERT INTO co.t_ingredients VALUES (37, 'absinthe');
INSERT INTO co.t_ingredients VALUES (38, 'bénédictine');
INSERT INTO co.t_ingredients VALUES (39, 'peychaud''s bitters');
INSERT INTO co.t_ingredients VALUES (40, 'prosecco');
INSERT INTO co.t_ingredients VALUES (41, 'peach');
INSERT INTO co.t_ingredients VALUES (42, 'vodka');
INSERT INTO co.t_ingredients VALUES (43, 'cl');
INSERT INTO co.t_ingredients VALUES (44, 'worcestershire sauce');
INSERT INTO co.t_ingredients VALUES (45, 'tabasco sauce');
INSERT INTO co.t_ingredients VALUES (46, 'celery salt');
INSERT INTO co.t_ingredients VALUES (47, 'black pepper');
INSERT INTO co.t_ingredients VALUES (48, 'cointreau');
INSERT INTO co.t_ingredients VALUES (49, 'lime juice');
INSERT INTO co.t_ingredients VALUES (50, 'cranberry juice');
INSERT INTO co.t_ingredients VALUES (51, 'champagne');
INSERT INTO co.t_ingredients VALUES (52, 'simple syrup');
INSERT INTO co.t_ingredients VALUES (53, 'amaretto');
INSERT INTO co.t_ingredients VALUES (54, 'orange-flavored liqueur');
INSERT INTO co.t_ingredients VALUES (55, 'galliano');
INSERT INTO co.t_ingredients VALUES (56, 'wine');
INSERT INTO co.t_ingredients VALUES (57, 'white wine');
INSERT INTO co.t_ingredients VALUES (58, 'crème de cassis');
INSERT INTO co.t_ingredients VALUES (59, 'grapefruit juice');
INSERT INTO co.t_ingredients VALUES (60, 'tequila');
INSERT INTO co.t_ingredients VALUES (61, 'grenadine syrup');
INSERT INTO co.t_ingredients VALUES (62, 'lillet blanc');
INSERT INTO co.t_ingredients VALUES (63, 'falernum');
INSERT INTO co.t_ingredients VALUES (64, 'pernod');
INSERT INTO co.t_ingredients VALUES (65, 'pineapple juice');
INSERT INTO co.t_ingredients VALUES (66, 'mezcal');
INSERT INTO co.t_ingredients VALUES (67, 'yellow chartreuse');
INSERT INTO co.t_ingredients VALUES (68, 'aperol');
INSERT INTO co.t_ingredients VALUES (69, 'amaro');
INSERT INTO co.t_ingredients VALUES (70, 'whisky');
INSERT INTO co.t_ingredients VALUES (71, 'blended scotch whisky');
INSERT INTO co.t_ingredients VALUES (72, 'lagavulin 16y whisky');
INSERT INTO co.t_ingredients VALUES (73, 'irish whiskey');

SELECT pg_catalog.setval('co.t_ingredients_ingredient_id_seq', 73, true);








INSERT INTO co.t_cocktails VALUES (1, 'Alexander', 'https://en.wikipedia.org/wiki/Alexander_(cocktail)');
INSERT INTO co.t_cocktails VALUES (2, 'Americano', 'https://en.wikipedia.org/wiki/Americano_(cocktail)');
INSERT INTO co.t_cocktails VALUES (3, 'Angel Face', 'https://en.wikipedia.org/wiki/Angel_Face_(cocktail)');
INSERT INTO co.t_cocktails VALUES (4, 'Aviation', 'https://en.wikipedia.org/wiki/Aviation_(cocktail)');
INSERT INTO co.t_cocktails VALUES (5, 'Between the Sheets', 'https://en.wikipedia.org/wiki/Between_the_Sheets_(cocktail)');
INSERT INTO co.t_cocktails VALUES (6, 'Boulevardier', 'https://en.wikipedia.org/wiki/Boulevardier_(cocktail)');
INSERT INTO co.t_cocktails VALUES (7, 'Casino', 'https://en.wikipedia.org/wiki/Casino_(cocktail)');
INSERT INTO co.t_cocktails VALUES (8, 'Dry Martini', 'https://en.wikipedia.org/wiki/Martini_(cocktail)');
INSERT INTO co.t_cocktails VALUES (9, 'Fizz', 'https://en.wikipedia.org/wiki/Fizz_(cocktail)#Gin_fizz');
INSERT INTO co.t_cocktails VALUES (10, 'John Collins', 'https://en.wikipedia.org/wiki/John_Collins_(cocktail)');
INSERT INTO co.t_cocktails VALUES (11, 'The Last Word', 'https://en.wikipedia.org/wiki/Last_Word_(cocktail)');
INSERT INTO co.t_cocktails VALUES (12, 'Manhattan', 'https://en.wikipedia.org/wiki/Manhattan_(cocktail)');
INSERT INTO co.t_cocktails VALUES (13, 'Martinez', 'https://en.wikipedia.org/wiki/Martinez_(cocktail)');
INSERT INTO co.t_cocktails VALUES (14, 'Mary Pickford', 'https://en.wikipedia.org/wiki/Mary_Pickford_(cocktail)');
INSERT INTO co.t_cocktails VALUES (15, 'Old fashioned', 'https://en.wikipedia.org/wiki/Old_fashioned_(cocktail)');
INSERT INTO co.t_cocktails VALUES (16, 'Paradise', 'https://en.wikipedia.org/wiki/Paradise_(cocktail)');
INSERT INTO co.t_cocktails VALUES (17, 'Fizz', 'https://en.wikipedia.org/wiki/Fizz_(cocktail)#Ramos_gin_fizz');
INSERT INTO co.t_cocktails VALUES (18, 'Rusty Nail', 'https://en.wikipedia.org/wiki/Rusty_Nail_(cocktail)');
INSERT INTO co.t_cocktails VALUES (19, 'Sidecar', 'https://en.wikipedia.org/wiki/Sidecar_(cocktail)');
INSERT INTO co.t_cocktails VALUES (20, 'Stinger', 'https://en.wikipedia.org/wiki/Stinger_(cocktail)');
INSERT INTO co.t_cocktails VALUES (21, 'Tuxedo', 'https://en.wikipedia.org/wiki/Tuxedo_(cocktail)');
INSERT INTO co.t_cocktails VALUES (22, 'Vieux Carré', 'https://en.wikipedia.org/wiki/Vieux_Carr%C3%A9_(cocktail)');
INSERT INTO co.t_cocktails VALUES (23, 'White Lady', 'https://en.wikipedia.org/wiki/White_Lady_(cocktail)');
INSERT INTO co.t_cocktails VALUES (24, 'Bellini', 'https://en.wikipedia.org/wiki/Bellini_(cocktail)');
INSERT INTO co.t_cocktails VALUES (25, 'Bloody Mary', 'https://en.wikipedia.org/wiki/Bloody_Mary_(cocktail)');
INSERT INTO co.t_cocktails VALUES (26, 'Cosmopolitan', 'https://en.wikipedia.org/wiki/Cosmopolitan_(cocktail)');
INSERT INTO co.t_cocktails VALUES (27, 'French 75', 'https://en.wikipedia.org/wiki/French_75_(cocktail)');
INSERT INTO co.t_cocktails VALUES (28, 'French Connection', 'https://en.wikipedia.org/wiki/French_Connection_(cocktail)');
INSERT INTO co.t_cocktails VALUES (29, 'Golden Dream', 'https://en.wikipedia.org/wiki/Golden_dream_(cocktail)');
INSERT INTO co.t_cocktails VALUES (30, 'Grasshopper', 'https://en.wikipedia.org/wiki/Grasshopper_(cocktail)');
INSERT INTO co.t_cocktails VALUES (31, 'Kir', 'https://en.wikipedia.org/wiki/Kir_(cocktail)');
INSERT INTO co.t_cocktails VALUES (32, 'Mimosa', 'https://en.wikipedia.org/wiki/Mimosa_(cocktail)');
INSERT INTO co.t_cocktails VALUES (33, 'Sea Breeze', 'https://en.wikipedia.org/wiki/Sea_Breeze_(cocktail)');
INSERT INTO co.t_cocktails VALUES (34, 'Tequila sunrise', 'https://en.wikipedia.org/wiki/Tequila_sunrise_(cocktail)');
INSERT INTO co.t_cocktails VALUES (35, 'Vesper', 'https://en.wikipedia.org/wiki/Vesper_(cocktail)');
INSERT INTO co.t_cocktails VALUES (36, 'Zombie', 'https://en.wikipedia.org/wiki/Zombie_(cocktail)');
INSERT INTO co.t_cocktails VALUES (37, 'Barracuda', 'https://en.wikipedia.org/wiki/Barracuda_(cocktail)');
INSERT INTO co.t_cocktails VALUES (38, 'Bee''s Knees', 'https://en.wikipedia.org/wiki/Bee%27s_Knees_(cocktail)');
INSERT INTO co.t_cocktails VALUES (39, 'Bramble', 'https://en.wikipedia.org/wiki/Bramble_(cocktail)');
INSERT INTO co.t_cocktails VALUES (40, 'Illegal', 'https://en.wikipedia.org/wiki/Illegal_(cocktail)');
INSERT INTO co.t_cocktails VALUES (41, 'Lemon Drop Martini', 'https://en.wikipedia.org/wiki/Lemon_drop_(cocktail)');
INSERT INTO co.t_cocktails VALUES (42, 'Naked and Famous', 'https://en.wikipedia.org/wiki/Naked_and_Famous_(cocktail)');
INSERT INTO co.t_cocktails VALUES (43, 'Paloma', 'https://en.wikipedia.org/wiki/Paloma_(cocktail)');
INSERT INTO co.t_cocktails VALUES (44, 'Paper Plane', 'https://en.wikipedia.org/wiki/Paper_Plane_(cocktail)');
INSERT INTO co.t_cocktails VALUES (45, 'Penicillin', 'https://en.wikipedia.org/wiki/Penicillin_(cocktail)');
INSERT INTO co.t_cocktails VALUES (46, 'South Side or Southside', 'https://en.wikipedia.org/wiki/South_Side_(cocktail)');
INSERT INTO co.t_cocktails VALUES (47, 'Tipperary', 'https://en.wikipedia.org/wiki/Tipperary_(cocktail)');
INSERT INTO co.t_cocktails VALUES (48, 'Yellow Bird', 'https://en.wikipedia.org/wiki/Yellow_Bird_(cocktail)');


SELECT pg_catalog.setval('co.t_cocktails_cocktail_id_seq', 48, true);





INSERT INTO co.t_cocktails_x_t_ingredients VALUES (1, 1);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (1, 2);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (1, 3);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (2, 4);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (2, 5);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (2, 6);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (3, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (3, 8);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (3, 9);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (4, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (4, 10);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (4, 11);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (5, 1);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (5, 12);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (5, 13);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (5, 14);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (5, 15);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (6, 16);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (6, 4);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (6, 5);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (6, 17);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (7, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (7, 10);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (7, 18);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (8, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (8, 4);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (9, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (9, 19);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (9, 12);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (10, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (10, 15);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (10, 20);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (10, 21);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (11, 22);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (11, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (11, 23);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (11, 24);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (11, 25);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (12, 19);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (12, 26);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (12, 4);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (12, 27);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (13, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (14, 12);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (14, 28);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (14, 10);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (15, 19);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (15, 17);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (15, 29);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (15, 30);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (15, 31);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (16, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (16, 32);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (16, 33);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (17, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (17, 19);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (17, 12);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (18, 34);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (18, 35);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (19, 1);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (19, 13);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (19, 15);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (20, 1);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (20, 36);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (21, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (21, 4);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (21, 10);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (21, 37);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (21, 18);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (22, 26);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (22, 1);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (22, 4);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (22, 38);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (22, 39);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (23, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (23, 13);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (24, 40);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (24, 41);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (25, 42);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (25, 43);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (25, 15);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (25, 44);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (25, 45);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (25, 46);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (25, 47);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (26, 42);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (26, 48);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (26, 49);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (26, 50);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (27, 51);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (27, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (27, 52);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (27, 15);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (28, 1);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (28, 53);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (29, 54);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (29, 55);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (29, 13);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (29, 33);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (29, 3);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (30, 2);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (30, 36);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (30, 3);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (31, 56);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (31, 57);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (31, 58);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (32, 51);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (32, 33);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (33, 42);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (33, 50);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (33, 59);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (34, 60);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (34, 33);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (34, 61);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (35, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (35, 42);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (35, 62);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (36, 12);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (36, 23);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (36, 63);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (36, 28);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (36, 27);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (36, 64);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (37, 12);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (37, 55);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (37, 65);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (37, 49);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (37, 40);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (38, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (39, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (39, 15);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (39, 52);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (40, 66);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (40, 12);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (40, 63);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (40, 10);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (40, 23);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (40, 52);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (41, 42);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (42, 66);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (42, 67);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (42, 68);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (42, 23);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (43, 60);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (44, 16);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (44, 69);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (44, 68);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (45, 70);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (45, 71);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (45, 72);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (46, 7);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (47, 73);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (47, 4);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (47, 24);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (47, 27);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (48, 12);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (48, 14);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (48, 55);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (48, 13);
INSERT INTO co.t_cocktails_x_t_ingredients VALUES (48, 49);

SELECT pg_catalog.setval('co.t_cocktails_x_t_ingredients_cocktail_id_seq', 1, false);
